# Generated by Django 4.2.3 on 2023-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
