# Generated by Django 4.2.3 on 2023-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_personaldetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
